### ISSUE TITLE
Underlying philosophy 

### ISSUE THREAD

**Issue by IwanKaramazow** [bbarr/medium#1]
Why use promises at all? Aren't channels (or CSP in general) a way of avoiding promises?
CSP + promises = two abstractions instead of one?

Seems like promises solve the inversion of control problem inherent with callbacks, but does it change it's fundamental nature, i.e. upon a certain event, an arbitrary amount of code is called...

I'm just curious.

**Comment by bbarr** [comment]
Hey @IwanKaramazow, sorry for the long delay.. 

So, CSP calls for our code to be able to "park", and wait for a `take` or a `put` to resolve. It might look something like this in Go:

```
x := <- ch
// this code looks synchronous, but won't run
// until x has asynchronously "taken" a value from ch
fmt.Println(x)
```

In Javascript, the best way we have to achieve this effect is to use the `async`/`await` keywords.

```
// javascript
let x = await take(ch)
// this code looks synchronous, but won't run
// until x has asynchronously "taken" a value from ch
console.log(x)
```

And `await` relies on being given promises. 

So, I think it is less about competing abstractions, and more about building one on top of another.. CSP needs a way to deal with future values, and promises provide that.

**Comment by trusktr** [comment]
@IwanKaramazow How would you implement this without promises, considering that async/await is built around Promises?

@bbarr Was there any specific reason to use the `go` function? The advantage of async/await over generators is that it's possible to do this without the extra `go` wrapper, which I feel is cleaner. Here's an example using [async-csp](https://www.npmjs.com/package/async-csp):

``` js
import Channel from 'async-csp'

async function sleep(duration) {
    return new Promise(resolve => setTimeout(resolve, duration))
}

async function player(name, table) {
    while (true) {
        var ball = await table.take()
        if (ball === Channel.DONE) {
            console.log(name + ": table's gone")
            return
        }
        ball.hits += 1
        console.log(name + " " + ball.hits)
        await sleep(100)
        await table.put(ball)
    }
}

~async function() {
    var table = new Channel()

    player("ping", table)
    player("pong", table)

    await table.put({hits: 0})
    await sleep(1000)
    table.close()
}()
```

**Comment by bbarr** [comment]
@trusktr You are right that it is not needed.. just a little helper that maybe is more confusing than it is worth.

`go` does nothing more than execute a function given it:

```
function go(afn) { return afn() }
```

So, it is in fact borderline useless, but I found it somewhat cleaner looking for kicking up a bunch of independent async processes.

```
go(async function() { ... })
(async function() { ... })()
```

_shrug_ It is an underwhelming argument for it, and my intention with Medium was to create the simplest API possible, so if it is found confusing for people, I really should just remove it.

For fun, I translated the above async-csp code to Medium (not tested).

```
import { put, take, sleep, ch, CLOSED, repeatTake } from 'medium'

async function player(name, table) {
    repeatTake(table, async (ball) => {
      if (ball === CLOSED) {
          console.log(name + ": table's gone")
          return false
      }
      ball.hits += 1
      console.log(name + " " + ball.hits)
      await sleep(100)
      await put(table, ball)
    })
}

go(async () => {
    var table = ch()

    player("ping", table)
    player("pong", table)

    await put(table, { hits: 0 })
    await sleep(1000)
    table.close()
})
```

**Comment by IwanKaramazow** [comment]
@trusktr I wouldn't be using promises at all, just pure csp ;) Promises & channels are two abstractions, why use two if you'll probably could get away with one abstraction in most scenarios... Every abstraction has a cost. In the meantime promises have become almost standard, I only use csp in more complex async scenario's were promises aren't much fun... 

I do like to use a `go`-block when using csp-channels, it's like a flag in my code to point out I'm using csp.

**Comment by bbarr** [comment]
@IwanKaramazow would be interested in seeing an implementation of this "pure csp"! As of the moment, I can't quite imagine how your solution would look..

**Comment by IwanKaramazow** [comment]
This 'pure csp' is just I javascript csp library that doesn't care about promise, nor uses them ;) Currently I'm using https://github.com/ubolonton/js-csp

For example when there are node style callback functions, I put the result (either error, or valid response) on a channel to take from.

Example:

``` javascript
// oldskool node-style callback
function queryDatabase(query, (err, res) => {
   if (err) // do stuff with err
   // handle res
});

// with js-scp
function toChan(ctx, func, ...args)  {
  const ch = chan();

  args.push( (err, res) => {
    go(function* () {
       if(err) put(ch, err);
       else   put(ch, res);
    });
  }
  func.apply(ctx, args);
  return ch;
}

// with the above function you get something like
go(function*(){
  const result = yield toChan(null, queryDatabase, query);  // yielding a channel is an implicit take
 // handle database query result
});

```

This is the kind of code I was using throughout my 'no-promises-only-csp' style code.
It was more of an excuse to learn csp :)
I wrote the code out of the top of my head here, no idea if it works exactly as it should, but you get the idea.

**Comment by bbarr** [comment]
Ah, so really though, the only difference here is that you are using a node-style callback. Since this is a one-and-done channel, just have queryDatabase return a promise! Then use async/await to resolve it directly.

``` javascript
// if queryDatabase returned a promise instead of using a node-style callback...
go(async () => {
  const result = await queryDatabase(query)
})
```

I love channels, but I think the above is vastly less complicated, no? Simply avoiding promises doesn't mean you aren't still having to solve the async problem.

**Comment by IwanKaramazow** [comment]
Yes, you're right, I absolutely complicate things. The main use case were all my libraries used node-style callbacks at the moment and didn't return promises. When refactoring a few months laters I converted them to promises:

``` javascript
function toPromise(ctx, func, ...args) {
  return new Promise((resolve, reject) => {
    args.push((err, res)=> {
      if (err) reject(err);
      else resolve(res);
    });
    func.apply(ctx, args);
  });
}
```

I just use `async` functions with `await` most of the time, channels overcomplicate simple promise handling.

**Comment by trusktr** [comment]
@IwanKaramazow But with the async/await/Promise method of implementing this, we can write

``` js
  args.push( (err, res) => {
    go(function* () {
       if(err) put(ch, err);
       else   put(ch, res);
    });
  }
```

as

``` js
  args.push( async (err, res) => {
    if(err) put(ch, err);
    else   put(ch, res);
  }
```

which is cleaner and shorter. I wonder what the performance considerations of one vs the other are. I might be inclined to switch over only if the generator approach without Promises is substantially faster.

> channels overcomplicate simple promise handling.

Not at all. If you're using a CSP implementation, then Promises are irrelevant because the end user is handling channels, not promises, and the implementation of the channels doesn't matter in that case. It's also really easy wrap a callback function with an async function returning a `Promise`, the result of which is cleaner code than with generators.

@jlongster might be able to [provide us with some insight](https://github.com/ubolonton/js-csp/issues/73) on why the generator approach without Promises might be advantageous. So far the claim is that without Promises the implementer has more control of the scheduler, but (as an end user of these CSP concepts myself, not an implementer) I don't yet see how the no-promise approach is advantageous to end users of CSP.
