### ISSUE TITLE
Good stuff!

### ISSUE THREAD

**Issue by idibidiart** [bbarr/medium#11]
Thanks for sharing this. Terrific work. Will be watching :) 

Does this diverge from ClojureScript's core.async implementation of CSP in any tangible way?

**Comment by bbarr** [comment]
Thanks so much for the encouragement! 

Medium was really about writing the simplest CSP implementation with the most readable source that I could. Thus, while it is heavily inspired by core.async, there is likely some drift in the API.

**Comment by idibidiart** [comment]
Ok, will provide feedback if I encounter any issues. Thanks again! Closing :-)
