### ISSUE TITLE
Closing channel purges any buffered items

### ISSUE THREAD

**Issue by jayjanssen** [bbarr/medium#15]
See code below.  

```
#!/usr/bin/env coffee

Promise = require 'bluebird'
util = require 'util'
medium = require 'medium'

get_something = () ->
  chan = medium.chan medium.buffers.fixed 2
  Promise.each [1..10], (i) ->
    medium.put chan, {test: i}
    .then () ->
      console.log "Sent: #{i}"

  .then () ->
    medium.close chan
  return chan

read = get_something()
medium.repeatTake read, (obj) ->
  return false if obj == medium.CLOSED

  console.log util.inspect obj

  Promise.delay 1000
.then () ->
  console.log "CLOSED"
```

The output I get from this is:

> Sent: 1
> { test: 1 }
> Sent: 2
> Sent: 3
> Sent: 4
> { test: 2 }
> Sent: 5
> { test: 3 }
> Sent: 6
> { test: 4 }
> Sent: 7
> { test: 5 }
> Sent: 8
> { test: 6 }
> Sent: 9
> { test: 7 }
> Sent: 10
> { test: 8 }
> CLOSED

Essentially the bug (I think, if I remember my Go correctly) is that once the channel gets closed here, I lose my objects for 9 and 10.

**Comment by bbarr** [comment]
@jayjanssen You are right. Going to take a spin at resolving this tonight... The channel should continue to hold buffered items and respond to `take`s even after being closed.

**Comment by bbarr** [comment]
Just ran your example code above, and it correctly pulls objects 9 and 10 as well.
