### ISSUE TITLE
go vs simple call

### ISSUE THREAD

**Issue by ivan-kleshnin** [bbarr/medium#6]
``` js
go(async function () {...}) // go style
(async function () {...})() // call style
```
#### Benefits
1. Immediately visible that it's not just declaration.<br/>
   Counter-argument: opening paren can be viewed as a call sign as well.
2. Similar to Clojure / Go (easier to adapt examples)
#### Drawbacks:
1. Excessive
2. Feels like it's just to mimick Clojure / Go syntax 
3. Currently, does not support arguments passing

Your opinion?

**Comment by bbarr** [comment]
Ultimately, there is another benefit that will keep `go` around, I think:

``` javascript
const a = 1
go(async () => {})
// works

const b = 1;
(async () => {})()
// works

const c = 1
(async () => {})()
// blows up
```

And I don't want to force anyone, especially me, to use semi-colons :)

**Comment by bbarr** [comment]
Drawback 3. is interesting.. I am curious if you would find this useful, and if so, would you want the arguments to come before the async function for easier binding (composing `go`s)?

Like:

``` javascript
const goWithFoo = R.partial(go, [ 'foo' ])
const goWithBar = R.partial(go, [ 'bar' ])

goWithFoo(async (foo) => ...)
goWithBar(async (bar) => ...)
```

Thoughts?

**Comment by ivan-kleshnin** [comment]
> And I don't want to force anyone, especially me, to use semi-colons :)

Haha, yeah, that's interesting! :smiley: 
I still use semicolons so I never thought of that aspect.

> I am curious if you would find this useful, and if so, would you want the arguments to come before the async function for easier binding (composing gos)?

Yes, I believe it's may be useful, but I'm not sure how. 
Need to try this out.

**Comment by lucasmreis** [comment]
I personally like the `go` abstraction, even though it does not do much :) 

It makes it very clear that a process was started. You know the code will be run asynchronously, just like with `setTimeout`.

I would no bother if it was named `spawn` either.
