### ISSUE TITLE
Bind syntax is stage-0

### ISSUE THREAD

**Issue by ivan-kleshnin** [bbarr/medium#7]
Despite being marked as **strawman** http://wiki.ecmascript.org/doku.php?id=strawman:bind_operator

``` js
{
  "presets": ["es2015", "stage-1"]
}
```

gives me

```
SyntaxError: ... Unexpected token 
take(ch1).then(::console.log);
```

with this package.json

``` js
"dependencies": {
  "babel-cli": "^6.5.1",
  "babel-polyfill": "^6.5.0",
  "babel-preset-es2015": "^6.5.0",
  "babel-preset-stage-0": "^6.5.0",
  "babel-preset-stage-1": "^6.5.0",
  ...
}
```

While the next works:

``` js
{
  "presets": ["es2015", "stage-0"]
}
```

Strange! :worried:

**Comment by bbarr** [comment]
Bumped package.json to stage-0.. `::` syntax isn't being used at the moment, but it could be now.
