### ISSUE TITLE
API discussion

### ISSUE THREAD

**Issue by ivan-kleshnin** [bbarr/medium#8]
So you've imlemented `takeRepeat` which is cool way to describe data producing...

I don't know how you take it but actually we're entering the realm of [Codata](https://en.wikipedia.org/wiki/Corecursion) here.

So I'd like to compare and discuss API possibilities we have. 

Relevant links:
http://ramdajs.com/0.19.1/docs/#unfold
https://www.haskell.org/hoogle/?hoogle=iterate
https://www.haskell.org/hoogle/?hoogle=scan
https://www.haskell.org/hoogle/?hoogle=unfold
http://package.elm-lang.org/packages/elm-lang/core/1.1.0/Signal#foldp
http://rxmarbles.com/#scan

For every above case we can mentally substitute `Array` / `List` / `Signal` with `Channel`. 
So let's lay out our possible API candidates from less complex to more complex.
### `iterate`

`iterate` returns a Channel, producing repeated applications of `f` to `x`
In other words, it generates sequence of values from static value.
##### Formal type

```
iterate:: (a -> a) -> a -> Channel a
```
##### Examples

```
IN:  x
OUT: x---f(x)---f(f(x))--->
```

Signature: `function iterate(iterateFn, seed)`. 
Call: `let ch = iterate(plusOne, 1)`. 

The obvious problem is that it's not reasonable to produce values without timeouts.
First solution: inject timeout into producer. By adding it, we start to approach [`RxJS.interval`](http://reactivex.io/documentation/operators/interval.html) concept. Second solution: require timeout in consumer, keeping `iterate` as proposed. We still can build rx-like `interval` on top of it.

Here I want to emphasize the similarity between Haskell API and possible Medium API, not
the timeout question which is secondary.
### `unfold`

`unfold` returns a Channel, producing repeated applications of `f` to `x`
In other words, it generates sequence of values from static value just as `iterate`.
The difference is that break support (sequence can be stopped by returning some guard value from producing function). `unfold` allows us to produce endable channels from seed values.
##### Formal type

```
unfold :: (b -> Maybe [a, b]) -> b -> Channel a
```

`Maybe` can be implemented in common JS way: `[a, b] | null`.
##### Examples

```
IN:  x
OUT: x---f(x)[0]---f(f(x))[0]---|>
```

Signature: `function unfold(unfoldFn, seed)`. 
Call: `let ch = unfold(unfoldFn, 1)`. 
### `scan`

`scan` returns a Channel, producing repeated applications of `f` to input Channel and some inner state.
In other words, it generates output values of input values, keeping state inside. Buffers and other crucial stuff can be implemented on top of it.

It does not support breaks in this version (see comment in the end).
##### Formal type

```
scan :: (a -> b -> a) -> a -> Channel b -> Channel a
```
##### Examples

Signature: `function scan(scanFn, seed, ch)`. 
Call: `let ch = scan(sum, 0, x)`. 

```
IN:  x1------------x2-------------------x3--------------------------
OUT: f(seed, x1)---f(f(seed, x1), x2)---f(f(f(seed, x1), x2), x3)---
```

**This is basically your `repeatTake` in more formal representation.** 
And the reason I started this write-up.
### Other possibilities

We can also want to have:
1. Version of `scan` with break support.
2. Version of `scan` which allows to "emit" one value, while keeping state with another value.
Example usage: emit sliding average, keeping buffer of actual values inside. See [`Most.loop`](https://github.com/cujojs/most/blob/master/docs/api.md#loop).

I like your promise- and channel- related API  very much but I'd love to have more formally implemented operators. Not only for codata, of course, just those ones are the hardest.

My personal opinion is that Clojure-like builtin support for transducers pushes us to build more imperative APIs with fewer channels (which is good for performance but not for readability).
See [CSP vs FRP](http://potetm.github.io/2014/01/07/frp.html).

We can also try to emulate FRP approach with tons of operators.
See [RxJS](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/categories.md)

And we have a freedom to stay in the middle, providing the most basic operators and allowing people to build with more complex ones on top of that. And this is probably my favorite option.

What's your vision of this?

**Comment by ivan-kleshnin** [comment]
To put it another way. Should we implement every possible generative function as channel or not?
If not – where is the borderline?

``` js
import {chan, put, sleep, take} from "medium";

let iterate = function (fn, seed) {
  let outChan = chan();
  let acc = seed;
  (async function () {
    while (true) {
      await put(outChan, acc);
      acc = fn(acc);
    }
  })();
  return outChan;
};

let ch = iterate(x => x + 1, 0);

// Interval implementation
(async function () {
  while (true) {
    console.log(await take(ch)); // 0-1-2-3-4-5...
    await sleep(100);
  }
})();
```

Using [ImLazy](https://github.com/benji6/imlazy). 

``` js
import {iterate} from "imlazy";

let gen = iterate(x => x + 1, 0); // generator of 0..1..2..

// Interval implementation
(async function () {
  console.log(get.next()); // 0-1-2-3-4-5...
  await sleep(1000);
})();
```

**Comment by bbarr** [comment]
OK, I am just sitting down to read through this, but from what I gather right away, I am also leaning towards the "middle path". Will read through this a bit more, then respond further.

**Comment by ivan-kleshnin** [comment]
@bbarr – sure. No problem, no hurry.

**Comment by ivan-kleshnin** [comment]
@lucasmreis, @bbarr 

Just for a record:

Here I'm comparing API for different FRP implementations:
https://github.com/ivan-kleshnin/reactive-polyglot
my goal is to discover a minimal set of operators to implement others on top of it.

I'm interested in operators because it's the most basic CSP application you can think of.

Here I'm trying to sketch and implement them, using Medium API.
https://github.com/ivan-kleshnin/csp-frp-foundation

I think the possible usage of generators is what most FRP implementations overlook.

The interesting (or obvious) point here is that quite soon I hit all the questions classic stream-based FRP address. Exceptions are a win of course. "Unicast vs Multicast" is solvable. Not sure how "Cold vs Hot" is applicable because channel has no subscribers. That's the basic thing of it.

Something like that, not going to take much of your time guys – sorry for possible distraction :)

**Comment by bbarr** [comment]
@ivan-kleshnin ok, finally read through your initial comment. 

I really like the idea of conforming to broadly-understood specs when the functionality is essentially the same, ie: `repeatTake` vs. `scan`. Aside from making it easier to grok for those already familiar with `scan`, it actually does a better job of keeping channels as the main subject, and that is a plus for composability.

I have some slight concerns about an infinite producer, as it would be so easy for naive code to crash things.. but, I am open to seeing how it feels. Could also do something like put a configurable cap on synchronous "takes" on an `iterate`-made channel.. throw a warning, and close the channel, if you don't release the thread occasionally.

For the question of "how many operators", I think I would like to aim for enough to make channels an enticing abstraction, but not enough to make me wish we had a stripped down version of medium. Perhaps additional functionality could be bundled up in a `channel-utils`-style project.. Is there a good library for these operators that could be configured to work with a channel-like object? If not, that could be interesting, decoupled from medium, and usable by any async/await channel library.

Anyway, scan/unfoldr/etc seem basic enough to include, so I am going to work on a new branch to test them out.. Would love feedback or contributions, of course, and thanks for bringing this all up!

**Comment by bbarr** [comment]
@ivan-kleshnin just checking out the other links now, too.. will star and follow along, I really like where you are heading with it.

**Comment by ivan-kleshnin** [comment]
@bbarr thank you. I just wanted to know how to do FRP. Turned out noone has a complete answer yet.
