### ISSUE TITLE
Channel CLOSED event / promise

### ISSUE THREAD

**Issue by ivan-kleshnin** [bbarr/medium#9]
https://github.com/dvlsg/async-csp#channeldone

Super simple use case: timing

``` js
console.time("sample");

let ch = chan();
go(async () => {
  await put(ch, "foo");  
  await put(ch, "bar");
  await sleep(1000);
  close(ch);
});

// ??? where to put ???
console.timeEnd("sample");
```

I'm not sure if `close` should be sync or async.

**Comment by lucasmreis** [comment]
I'm not sure what you are trying to measure here. Is it how long the goroutine lives? How long the channel lives?

**Comment by ivan-kleshnin** [comment]
> How long the channel lives?

This one. Time between channel start and end. Should take one second roughly.

**Comment by lucasmreis** [comment]
Oh ok, now I understand what you want here - it's something like a `.onclose` listener on a channel.

It's possible in Clojure to use "pub/subs" on channels, for exactly this kind of problem: https://github.com/clojure/core.async/wiki/Pub-Sub

I like the pub/sub being separated from the actual implementation, probably even another library. Could be something like:

``` js
sub(
  ch,                                   // channel to subscribe
  msg => msg.subject === 'someSubject', // condition to fire callback
  msg => console.log('Received:', msg)  // callback
) 
```

**Comment by bbarr** [comment]
In terms of how to time that, it is synchronous.. so, something like:

```
console.time("sample");
let ch = chan();
go(async () => {
  await put(ch, "foo");  
  await put(ch, "bar");
  await sleep(1000);
  close(ch);
  console.timeEnd("sample");
});
```

or:

```
console.time("sample");
let ch = chan();
go(async () => {
  await put(ch, "foo");  
  await put(ch, "bar");
  await sleep(1000);
  close(ch);
}).then(() =>  console.timeEnd("sample"));
```

should both work.

That is an interesting idea, making channels be event emitters... Could be used to signal when channel is closed, and also provide a way to get some operating details about the channel/buffering state, etc. I wonder if there are use-cases for any of that.

**Comment by ivan-kleshnin** [comment]
@lucasmreis, @bbarr maybe you're both right and I should measure async/await timing rather than channel. I can't remember an example which caused me to raise this issue so I'm going to close it until I'll have something to add.
